import { useState, useEffect } from "react";
import AppLayout from "components/AppLayout";
import Button from "components/Button";
import GitHub from "components/icons/github";
import Head from "next/head";

import { loginWithGitHub, onAuthStateChanged } from "fb/client";

import styles from "styles/Home.module.css";
import indexStyles from "styles/pages/index.module.css";

export default function Home() {
  const [user, setUser] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    onAuthStateChanged(setUser);
  }, []);

  const handleLogin = () => {
    loginWithGitHub()
      .then(setUser)
      .catch((err) => {
        console.log("Error");
        console.log(err);
      });
  };

  const handleLogout = () => {
    // if ( typeof user?.signOut === typeof Function ) {
    //   user.signOut().then(() => setUser(null)).catch(() => {
    //     setError('Could not logout')
    //   })
    // }
    user?.signOut();
    setUser(null);
  };

  return (
    <>
      <Head>
        <title>Devter 🐦</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        {error && <h1>{error}</h1>}
        <section className={indexStyles.home}>
          <img src="/devter-logo.png" alt="Logo" />
          <h1>Devter</h1>
          <h2>Developer's talk together 👩‍💻🧑‍💻👨‍💻</h2>

          <div>
            {user !== null ? (
              <div className={indexStyles.userinfo}>
                <div>
                  <img src={user?.avatar} alt={`${user?.username} avatar`} />
                  <h3>@{user?.username}</h3>
                </div>
                <Button onClick={handleLogout}>Logout</Button>
              </div>
            ) : (
              <Button onClick={handleLogin}>
                <GitHub fill="white" width="1em" height="1em" />
                Login with GitHub
              </Button>
            )}
          </div>
        </section>
      </AppLayout>

      <footer className={styles.footer}>
        <p>(c) 2022</p>
      </footer>
    </>
  );
}
