import AppLayout from 'components/AppLayout';
import Button from 'components/Button';
import GitHub from 'components/icons/github';
import { loginWithGitHub, onAuthStateChanged } from 'fb/client';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from 'styles/Home.module.css';
import indexStyles from 'styles/pages/index.module.css';
import devterLogo from '../../public/devter-logo.png';

export default function Home() {
  const [user, setUser] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    onAuthStateChanged(setUser);
  }, []);

  const handleLogin = () => {
    loginWithGitHub().then(setUser).catch(setError);
  };

  const handleLogout = () => {
    // if ( typeof user?.signOut === typeof Function ) {
    //   user.signOut().then(() => setUser(null)).catch(() => {
    //     setError('Could not logout')
    //   })
    // }
    user?.signOut();
    setUser(null);
  };

  return (
    <>
      <Head>
        <title>Devter 🐦</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        {error && <h1>{error}</h1>}
        <section className={indexStyles.home}>
          <figure>
            <Image src={devterLogo} alt="Logo" placeholder="blur" />
          </figure>

          <h1>Devter</h1>
          <h2>Developer&apos;s talk together 👩‍💻🧑‍💻👨‍💻</h2>

          <div>
            {user !== null ? (
              <div className={indexStyles.userinfo}>
                <div>
                  <figure className="avatar">
                    <Image
                      src={user?.avatar}
                      alt={`${user?.username} avatar`}
                      width={64}
                      height={64}
                      className={indexStyles.avatar}
                    />
                  </figure>
                  <h3>@{user?.username}</h3>
                </div>
                <Button onClick={handleLogout}>Logout</Button>
              </div>
            ) : (
              <Button onClick={handleLogin}>
                <GitHub fill="white" width="1em" height="1em" />
                Login with GitHub
              </Button>
            )}
          </div>
        </section>
      </AppLayout>

      <footer className={styles.footer}>
        <p>(c) 2022</p>
      </footer>
    </>
  );
}
