import Avatar from 'components/Avatar';
import Button from 'components/Button';
import GitHub from 'components/icons/github';
import Logo from 'components/icons/logo';
import Loading from 'components/Loading';
import { loginWithGitHub, logOut } from 'fb/client';
import useUser, { USER_STATES } from 'hooks/useUser';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import indexStyles from 'styles/pages/index.module.css';

export default function Home() {
  const { user } = useUser();
  const [error, setError] = useState(null);
  const router = useRouter();

  useEffect(() => {
    user && router.replace('/home');
  }, [user, router]);

  const handleLogin = () => {
    loginWithGitHub().catch(setError);
  };

  const handleLogout = () => {
    user && logOut();
  };

  return (
    <>
      <Head>
        <title>Devter 🐦</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {error && <h1>{error}</h1>}
      <div className={indexStyles.header}>
        <Logo />
        <h1>Devter</h1>
        <h2>Developer&apos;s talk together 👩‍💻🧑‍💻👨‍💻</h2>
      </div>
      <section className={indexStyles.home}>
        <div>
          {user === USER_STATES.NOT_LOGGED && (
            <Button onClick={handleLogin}>
              <GitHub fill="white" width="1em" height="1em" />
              Login with GitHub
            </Button>
          )}

          {user && (
            <div className={indexStyles.userinfo}>
              <Avatar
                src={user.avatar}
                alt={`${user?.username} avatar`}
                text={`@${user?.username}`}
              />
              <Button onClick={handleLogout}>Logout</Button>
            </div>
          )}
          {user === USER_STATES.NOT_KNOWN && <Loading size={50} />}
        </div>
      </section>
    </>
  );
}
